src/ECommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from services.views import home
from django.conf import settings 
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('uses/',include('accounts.urls')),
    path('services/', include('services.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path

from accounts.views import login_user , signup , logout_user , index
app_name="accounts"

urlpatterns = [
    
    path('',index , name="index"),
    path('signup/',signup ,name="signup"),
    path('login/',login_user ,name="login"),
    path('logout/',logout_user ,name="logout"),
         
]

src/services/urls.py
from django.urls import path
from services.views import HomeView  , ServiceCreateView , ServiceUpdateView , ServiceDeleteView , ServiceDetailView
app_name="services"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create/', ServiceCreateView.as_view() , name="create"),
    path('update/<int:pk>', ServiceUpdateView.as_view() , name="update"),
    path('delete/<int:pk>', ServiceDeleteView.as_view() , name="delete"),
    path('detail/<int:pk>', ServiceDetailView.as_view() , name="detail"),
]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,Group
# Create your models here.


class Customer(AbstractUser ):
 pass

src/services/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse
from django import forms

# Create your models here.

class Service(models.Model):
    title = models.CharField(max_length=200, verbose_name="Title")
    subtitle = models.CharField(max_length=200, verbose_name="Subtitle" , blank=True, null=True)
    pubished = models.BooleanField(verbose_name="Published", default=False)
    content = models.TextField(verbose_name="Content")
    image = models.ImageField(verbose_name="Image", upload_to="services/" , blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Updated")
    Appels = models.IntegerField(verbose_name="Appels", default=0)
    SMS = models.IntegerField(verbose_name="SMS", default=0)
    Prix = models.FloatField(verbose_name="Prix", default=0)
    Code = models.CharField(max_length=200, verbose_name="Code", default="")

    class Meta:
        verbose_name = "service"
        verbose_name_plural = "services"
        ordering = ["-created"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.subtitle = slugify(self.title)
        self.created = timezone.now()
        super(Service, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("services:home")

src/services/forms.py
from django import forms

from .models import Service


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('title', 'content', 'image', 'pubished',)
        title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'pubished': forms.CheckboxInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }
  
  

src/accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import get_user_model,login,logout,authenticate
from django.contrib.auth.decorators import login_required,permission_required

User= get_user_model()


def index (request):
  return render(request, 'accounts/index.html')


def signup (request):
    if request.method == 'POST':
      username= request.POST.get('username')
      password= request.POST.get('password')
      first_name= request.POST.get('first name')
      last_name=request.POST.get('last name')
      email=request.POST.get('email adress')
      user = User.objects.create_user(username=username , password=password ,
                                      first_name=first_name, last_name=last_name,
                                      email=email)
  

  
      login(request, user)    
      return redirect("services:home") 
    return render(request, 'accounts/signup.html')






def logout_user(request):
    logout(request)
    return redirect("accounts:index")




def login_user (request):
  
    if request.method=="POST":
      username= request.POST.get('username')
      password= request.POST.get('password')
      user =authenticate(username=username, password=password)
      if user:
        login(request,user)
        return redirect("accounts:index")
          
    return render(request, 'accounts/login.html')    

src/services/views.py
from django.shortcuts import render
from django.views.generic import ListView ,DetailView, CreateView , UpdateView , DeleteView
from django.urls import reverse_lazy
from .models import Service
from .forms import ServiceForm
from django.contrib.auth.decorators import login_required , user_passes_test 
from django.utils.decorators import method_decorator
# Create your views here.

from django.contrib.auth.models import Group
def home(request):
    return render(request, 'homeapp.html')


class HomeView(ListView):
    model = Service
    template_name = 'services\home.html'
    context_object_name = 'services'
    ordering = ['-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home'
        return context

class ServiceDetailView(DetailView):
    model = Service
    template_name = 'services\detail.html'
    context_object_name = 'service'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Detail'
        return context

@login_required
@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
class ServiceCreateView(CreateView):
    model = Service
    form_class = ServiceForm
    template_name = 'services\\create.html'
    success_url = reverse_lazy('services:home')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        return context

        
class ServiceUpdateView(UpdateView):
    model = Service
    template_name = 'services\\update.html'
    form_class = ServiceForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update'
        return context
    
class ServiceDeleteView(DeleteView):
    model = Service
    template_name = 'services\\delete.html'
    success_url = reverse_lazy('services:home')
    context_object_name = 'service'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete'
        return context

src/accounts/templates/accounts/index.html
{% extends 'base.html' %}


{% block content  %}
{% if user.is_authenticated %}
    <h1>bienvenue</h1><h2>{{user.username}}</h2>
    <a href="{% url 'accounts:logout' %}">Logout</a>
    {% endif %}
    <br><br>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}

  
{% block content %}
<form method="POST">
    
  {% csrf_token %}
 
   <div class="form-group">
     <label for="username" class="form-label mt-4">username</label>
     <input type="text" class="form-control"  placeholder="votre nom" name="username">
   </div>
   <div class="form-group">
         <label for="password" class="form-label mt-4">Password</label>
         <input type="password" class="form-control"  placeholder="Password" name="password">
       </div>
       <input type="submit" name="signup"  class =" btn btn-outline-warning"value="connnecter">
     </div>  
 </form>
{% endblock content %}

src/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
  

<form method="POST">
    
 {% csrf_token %}

<form>
    <fieldset class="container">
      <legend>inscription</legend>
      <div class="form-group row">
        <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
       
      </div>
      <div class="form-group">
        <label for="username" class="form-label mt-4">nom d'utiliateur</label>
        <input type="text" class="form-control"  placeholder="votre nom d'utiliateur" name="username">
      </div>

      <div class="form-group">
        <label for="first name" class="form-label mt-4">nom</label>
        <input type="text" class="form-control"  placeholder="votre nom" name="first name">
      </div>
      <div class="form-group">
        <label for="last name" class="form-label mt-4">prenom</label>
        <input type="text" class="form-control"  placeholder="votre prenom" name="last name">
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1" class="form-label mt-4">Email address</label>
        <input type="email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email"namz="email adress">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1" class="form-label mt-4">Password</label>
        <input type="password" class="form-control"  placeholder="Password" name="password">
      </div>
    
      <input type="submit" name="signup" value="s'inscrire" class=" btn btn-outline-warning" >
    </fieldset>
  </form>
{% endblock content %}

src/services/templates/services/create.html
{% extends 'base.html' %}

{% block title %}{% endblock %}


{% block content %}
<div class="container">
<h1 class=" mt-5" style="color: orangered;">Ajouter Un Service</h1>
    <div class="mt-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Créer">
        </form>
    </div>
</div>
{% endblock %}

src/services/templates/services/delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Supprimer un service</title>
{% endblock %}
    
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer le service {{ service.nom }} ?</p>
        <input type="submit" value="Oui" />

    </form>
{% endblock %}

src/services/templates/services/detail.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}
    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        {% block content %}
  <div class="container mt-3">
    <img src="{{ service.image.url }}" class="img-fluid" />
    <h1 style="margin-top: -50px ; color:#fd7e14; margin-left: 20px;">{{ service.title }}</h1>
    <div class="row justify-content-start">
      <div class="col-4 rounded-cricle" style="background-color: #fd7e14; color: rgb(0, 0, 0); margin-left: 20px;">
        {{service.Appels}} Mil/min
        <i class="fa-solid fa-user"></i>
      </div>
      <div class="col-4 rounded-cricle" style="background-color: #fd7e14; color: rgb(0, 0, 0); margin-left: 20px;">
        {{service.SMS}} Mil/sms
        <br>
        <small>Le moins cher</small>
      </div>
      <div class="col-2" style="margin-left: 120px;">
        <button class="btn btn-sm btn-block btn-primary px-lg-2" type="button">Choisir cette offre</button>
      </div>
    </div>
    <hr class="border-4" style="border : 4px solid #fd7e14; margin-top: 20px;" />
    <h1 class="h3 mb-4 mt-2">Détails et avantages de l'offre</h1>
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h4>Heading 1</h4>
          <p>Paragraph text</p>
        </div>
        <div class="col-md-2">
          <div class="d-flex justify-content-center align-items-center rounded-circle border" style="width: 100px; height: 100px; background-color: #fd7e14; color: rgb(0, 0, 0);">
            <p>Circle text</p>
          </div>
        </div>
        <div class="col-md-2">
          <div class="d-flex justify-content-center align-items-center rounded-circle border" style="width: 100px; height: 100px; background-color: #fd7e14; color: rgb(0, 0, 0); margin-left: -40px;">
            <p>Circle text</p>
          </div>
        </div>
        <div class="col-md-2">
          <div class="d-flex justify-content-center align-items-center rounded-circle border" style="width: 100px; height: 100px; background-color: #fd7e14; color: rgb(0, 0, 0); margin-left: -80px;">
            <p>Circle text</p>
          </div>
        </div>
      </div>
    </div>
    <hr class="border-4" style="border : 4px solid #fd7e14; margin-top: 20px;" />
    <h1 class="h3 mb-4 mt-2">Options</h1>
    <div class="card mb-3" style="max-width: 100%; margin-top: 20px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="https://mdbcdn.b-cdn.net/wp-content/uploads/2020/06/vertical.webp" class="img-fluid rounded-start" style="height: 80%;width: 100%;" />
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Bénéficiez également et en exclusivité des options:</h5>
            <p class="card-text">1.« Ena wayek » qui vous permettent de choisir un Numéro Favori de votre choix et profitez ainsi de 60 min par jour pour communiquer librement durant toute la journée avec une validité allant de 7 jours à un mois.

              Pour profiter des Options Ena Wayek composez le *105# Pour plus d’information cliquez ici.</p>
            <p class="card-text">
              <small class="text-muted">Pour plus d’information cliquez ici.</small>
            </p>
            <p>2.« Familti » qui vous permettent de choisir jusqu’à 5 membres pour former un groupe et partager entre vous, un forfait d’appels + Internet. Tous les membres du groupe peuvent s’appeler mais également se connecter librement et en toute sérénité entre eux en puisant dans les nouvelles options Familti Pour profiter des nouvelles options Familti, composez *225#</p>
            <p class="card-text">
              <small class="text-muted">Pour plus d’information cliquez ici.</small>
            </p>
          </div>
        </div>
      </div>
    </div>
    <hr class="border-4" style="border : 4px solid #fd7e14; margin-top: 20px;" />
    <h1 class="h3 mb-4 mt-2">Codes utiles</h1>
    <div class="card mb-3" style="max-width: 100%; margin-top: 20px;">
      <div class="row g-0">
        <div class="col-md-8">
          <div class="card-body">
            <ul class="list-group list-group-light">
              <li class="list-group-item d-flex justify-content-between align-items-center">
                A list item
                <span class="badge rounded-pill" style="background-color: #fd7e14; color: rgb(0, 0, 0);">*124*212542243#</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                A second list item
                <span class="badge rounded-pill" style="background-color: #fd7e14; color: rgb(0, 0, 0);">1</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                A third list item
                <span class="badge rounded-pill" style="background-color: #fd7e14; color: rgb(0, 0, 0);">1</span>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <img src="https://mdbcdn.b-cdn.net/wp-content/uploads/2020/06/vertical.webp" class="img-fluid rounded-start" style="height: 80%;width: 100%;" />
        </div>
      </div>
    </div>
    <hr class="border-4" style="border : 4px solid #fd7e14; margin-top: 20px;" />
    <h1 class="h3 mb-4 mt-2">Téléphones associés à cette offre</h1>
    <h6>Optez pour une formule en PACK</h6>
    <div class="row mt-2" style="margin-left: 2%">
      <div class="card mx-2" style="border : 3px solid black; margin-top: 20px;">
        <img src="phone-image.jpg" class="card-img-top" alt="Phone Image" />
        <div class="card-body">
          <h5 class="card-title">Phone Title</h5>
          <p class="card-text">ROM: 128GB, RAM: 6GB, Camera: 12MP</p>
          <hr class="border-4" style="border : 1px solid #fd7e14; margin-top: 20px;" />
          <p class="card-text">Price: $499.99</p>
          <button class="btn btn-primary">Add to Cart</button>
        </div>
      </div>
      <div class="card mx-2" style="border : 3px solid black; margin-top: 20px;">
        <img src="phone-image.jpg" class="card-img-top" alt="Phone Image" />
        <div class="card-body">
          <h5 class="card-title">Phone Title</h5>
          <p class="card-text">ROM: 128GB, RAM: 6GB, Camera: 12MP</p>
          <hr class="border-4" style="border : 1px solid #fd7e14; margin-top: 20px;" />
          <p class="card-text">Price: $499.99</p>
          <button class="btn btn-primary">Add to Cart</button>
        </div>
      </div>
      <div class="card mx-2" style="border : 3px solid black; margin-top: 20px;">
        <img src="phone-image.jpg" class="card-img-top" alt="Phone Image" />
        <div class="card-body">
          <h5 class="card-title">Phone Title</h5>
          <p class="card-text">ROM: 128GB, RAM: 6GB, Camera: 12MP</p>
          <hr class="border-4" style="border : 1px solid #fd7e14; margin-top: 20px;" />
          <p class="card-text">Price: $499.99</p>
          <button class="btn btn-primary">Add to Cart</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

src/services/templates/services/home.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
  <title>Services</title>
{% endblock %}
{% block content %}
  <section class="article-list">
    <div class="container">
        <div class="intro">
            <h2 class="text-center mt-2">Liste Des Services</h2>
        </div>
        <div class="row articles mt-5">
            {% for service in services %}
            <div class="col-md-4 col-sm-6 item">
                <a href="#"> 
                    <img class="img-responsive" src="{{service.image.url}}" alt="Image" style="height: 200px; width: 300px;">
                </a>
                <h3 class="name text-center ">{{service.title}}</h3>
                <p class="description">{{service.content|linebreaksbr|truncatechars:50}}</p>
                <a class=" text-center" href="{% url 'services:detail' service.id %}" 
                style="color: #fd7e14;"
                >Read More</a>
            </div>

            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

src/services/templates/services/update.html
{% extends 'base.html' %}

{% block title %}{% endblock %}


{% block content %}
<div class="container">
<h1 class=" mt-5" style="color: orangered;">Modifier un service</h1>
    <div class="mt-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Modifier" class="btn btn-primary">
        </form>
    </div>
</div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block title %}
    <title>Orange-TN</title>      
    {% endblock %}
</head>
<body>
    {% include 'nav.html' %}
    {% block content %}

    {% endblock %}

</body>
<script src="{% static 'js/jquery.min.js'%}"></script>
<script src="{% static 'js/popper.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="{% static 'js/main.js'%}"></script>
</html>

src/templates/homeapp.html
{% load static %}
{% block title %}
<title> Orange TN</title>
{% endblock %}

{% include 'base.html' %}
{% block content %}

{% endblock %}
<script src="{% static 'js/jquery.min.js'%}"></script>
<script src="{% static 'js/popper.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="{% static 'js/main.js'%}"></script>

src/templates/nav.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700,500,900'  type='text/css'>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="container-fluid mt-2">
    <div class="row justify-content-between">
        <div class="col-md-8 order-md-last">
            <div class="row">
                <div class="col-md-6 text-center">
                    <a class="navbar-brand" href="index.html">
                        <img src="{% static 'img/orangelogo.png'%}" alt="logo" width="50" height="50">
                    </a>
                </div>
                <div class="col-md-6 d-md-flex justify-content-end mb-md-0 mb-3" style="margin-top: 10px;">
                    <form action="#" class="searchform order-lg-last">
                        <div class="form-group d-flex" >
                            <input type="text" class="form-control pl-3" placeholder="Search">
                            <button type="submit" placeholder="" class="form-control search"><span
                                    class="fa fa-search"></span></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4 d-flex">
            <div class="social-media" style="margin-top: 10px;">
                <p class="mb-0 d-flex">
                    <a href="#" class="d-flex align-items-center justify-content-center"><span
                            class="fa fa-facebook"><i class="sr-only">Face</i></span></a>
                    <a href="#" class="d-flex align-items-center justify-content-center"><span
                            class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
                    <a href="#" class="d-flex align-items-center justify-content-center"><span
                            class="fa fa-instagram"><i class="sr-only">Instagram</i></span></a>
                    <a href="#" class="d-flex align-items-center justify-content-center"><span
                            class="fa fa-dribbble"><i class="sr-only">Dribbble</i></span></a>
                </p>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light " id="ftco-navbar">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
            aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav m-auto">
                <li class="nav-item active"><a href="{% url 'home' %}" class="nav-link">Home</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Page</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        <a class="dropdown-item" href="#">Page 1</a>
                        <a class="dropdown-item" href="#">Page 2</a>
                        <a class="dropdown-item" href="#">Page 3</a>
                        <a class="dropdown-item" href="#">Page 4</a>
                    </div>
                </li>
                <li class="nav-item"><a href="{% url 'services:home' %}" class="nav-link">Services</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Blog</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->